/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Yago Neno
 */
public class KeyboardScreen extends javax.swing.JFrame {

    // Instanciando um objeto da Classe 'Pangram'.
    Pangram objPangram = new Pangram();

    /**
     * Creates new form TelaTeclado
     */
    // Construtor.
    public KeyboardScreen() {
        setIcon();
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(java.awt.Color.black);
        UIManager.put("OptionPane.messageFont", new Font("Arial", Font.PLAIN, 14));
        UIManager.put("OptionPane.buttonFont", new Font("Arial", Font.PLAIN, 12));

        objPangram.setTextKeys(textArea);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPangram = new javax.swing.JButton();
        lblPangram = new javax.swing.JLabel();
        btnQuote = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnBackSpace = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnTab = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnAcute = new javax.swing.JButton();
        btnOpenBracket = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnCedilla = new javax.swing.JButton();
        btnTilde = new javax.swing.JButton();
        btnCloseBracket = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnCaps = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnComma = new javax.swing.JButton();
        btnPeriod = new javax.swing.JButton();
        btnSemiColon = new javax.swing.JButton();
        btnSlash = new javax.swing.JButton();
        btnBackSlash = new javax.swing.JButton();
        btnShift = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnSpace = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtual Keyboard");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        btnPangram.setBackground(new java.awt.Color(0, 0, 0));
        btnPangram.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPangram.setForeground(new java.awt.Color(255, 255, 255));
        btnPangram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-gear-white.png"))); // NOI18N
        btnPangram.setText(" Pangrama");
        btnPangram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPangramActionPerformed(evt);
            }
        });

        lblPangram.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPangram.setForeground(new java.awt.Color(255, 255, 255));

        btnQuote.setBackground(new java.awt.Color(0, 0, 0));
        btnQuote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQuote.setForeground(new java.awt.Color(255, 255, 255));
        btnQuote.setText("<html>\"<p>&nbsp; '</html>");
        btnQuote.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn1.setBackground(new java.awt.Color(0, 0, 0));
        btn1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("<html>!<p>&nbsp; 1</html>");
        btn1.setActionCommand("<html>!<br><strong>&nbsp;  1</html>");
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn1.setMinimumSize(new java.awt.Dimension(37, 43));

        btn4.setBackground(new java.awt.Color(0, 0, 0));
        btn4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("<html>$<p>&nbsp; 4</html>");
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn4.setMinimumSize(new java.awt.Dimension(37, 43));

        btn5.setBackground(new java.awt.Color(0, 0, 0));
        btn5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("<html>%<p>&nbsp; 5</html>");
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn5.setMinimumSize(new java.awt.Dimension(37, 43));

        btn3.setBackground(new java.awt.Color(0, 0, 0));
        btn3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("<html>#<p>&nbsp;  3</html>");
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn3.setMinimumSize(new java.awt.Dimension(37, 43));

        btn7.setBackground(new java.awt.Color(0, 0, 0));
        btn7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("<html>&<p>&nbsp; 7</html>");
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn7.setMinimumSize(new java.awt.Dimension(37, 43));

        btn8.setBackground(new java.awt.Color(0, 0, 0));
        btn8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("<html>*<p>&nbsp; 8</html>");
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn8.setMinimumSize(new java.awt.Dimension(37, 43));

        btn6.setBackground(new java.awt.Color(0, 0, 0));
        btn6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("<html>¨<p>&nbsp; 6</html>");
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn6.setMinimumSize(new java.awt.Dimension(37, 43));

        btnMinus.setBackground(new java.awt.Color(0, 0, 0));
        btnMinus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus.setText("<html>_<p>&nbsp;  -</html>");
        btnMinus.setActionCommand("<html>_<br>&nbsp; -</html>");
        btnMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMinus.setMinimumSize(new java.awt.Dimension(37, 43));

        btn9.setBackground(new java.awt.Color(0, 0, 0));
        btn9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("<html>(<p>&nbsp; 9</html>");
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn9.setMinimumSize(new java.awt.Dimension(37, 43));

        btnBackSpace.setBackground(new java.awt.Color(0, 0, 0));
        btnBackSpace.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBackSpace.setForeground(new java.awt.Color(255, 255, 255));
        btnBackSpace.setText("Backspace");
        btnBackSpace.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEquals.setBackground(new java.awt.Color(0, 0, 0));
        btnEquals.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEquals.setForeground(new java.awt.Color(255, 255, 255));
        btnEquals.setText("<html>+<p>&nbsp;  =</html>");
        btnEquals.setActionCommand("<html>+<br>&nbsp; =</html>");
        btnEquals.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEquals.setMinimumSize(new java.awt.Dimension(37, 43));

        btnTab.setBackground(new java.awt.Color(0, 0, 0));
        btnTab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTab.setForeground(new java.awt.Color(255, 255, 255));
        btnTab.setText("Tab");
        btnTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnE.setBackground(new java.awt.Color(0, 0, 0));
        btnE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnE.setForeground(new java.awt.Color(255, 255, 255));
        btnE.setText("E");
        btnE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnE.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnE.setMinimumSize(new java.awt.Dimension(37, 43));

        btnT.setBackground(new java.awt.Color(0, 0, 0));
        btnT.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnT.setForeground(new java.awt.Color(255, 255, 255));
        btnT.setText("T");
        btnT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnT.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnT.setMinimumSize(new java.awt.Dimension(37, 43));

        btnY.setBackground(new java.awt.Color(0, 0, 0));
        btnY.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnY.setForeground(new java.awt.Color(255, 255, 255));
        btnY.setText("Y");
        btnY.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnY.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnY.setMinimumSize(new java.awt.Dimension(37, 43));

        btnU.setBackground(new java.awt.Color(0, 0, 0));
        btnU.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnU.setForeground(new java.awt.Color(255, 255, 255));
        btnU.setText("U");
        btnU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnU.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnU.setMinimumSize(new java.awt.Dimension(37, 43));

        btnI.setBackground(new java.awt.Color(0, 0, 0));
        btnI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnI.setForeground(new java.awt.Color(255, 255, 255));
        btnI.setText("I");
        btnI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnI.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnI.setMinimumSize(new java.awt.Dimension(37, 43));

        btnO.setBackground(new java.awt.Color(0, 0, 0));
        btnO.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnO.setForeground(new java.awt.Color(255, 255, 255));
        btnO.setText("O");
        btnO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnO.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnO.setMinimumSize(new java.awt.Dimension(37, 43));

        btnP.setBackground(new java.awt.Color(0, 0, 0));
        btnP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnP.setForeground(new java.awt.Color(255, 255, 255));
        btnP.setText("P");
        btnP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnP.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnP.setMinimumSize(new java.awt.Dimension(37, 43));

        btnAcute.setBackground(new java.awt.Color(0, 0, 0));
        btnAcute.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAcute.setForeground(new java.awt.Color(255, 255, 255));
        btnAcute.setText("´");
        btnAcute.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAcute.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnAcute.setMinimumSize(new java.awt.Dimension(37, 43));

        btnOpenBracket.setBackground(new java.awt.Color(0, 0, 0));
        btnOpenBracket.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnOpenBracket.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenBracket.setText("[");
        btnOpenBracket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOpenBracket.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnOpenBracket.setMinimumSize(new java.awt.Dimension(37, 43));

        btnQ.setBackground(new java.awt.Color(0, 0, 0));
        btnQ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnQ.setForeground(new java.awt.Color(255, 255, 255));
        btnQ.setText("Q");
        btnQ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnQ.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnQ.setMinimumSize(new java.awt.Dimension(37, 43));

        btnF.setBackground(new java.awt.Color(0, 0, 0));
        btnF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnF.setForeground(new java.awt.Color(255, 255, 255));
        btnF.setText("F");
        btnF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnF.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnF.setMinimumSize(new java.awt.Dimension(37, 43));

        btnG.setBackground(new java.awt.Color(0, 0, 0));
        btnG.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnG.setForeground(new java.awt.Color(255, 255, 255));
        btnG.setText("G");
        btnG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnG.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnG.setMinimumSize(new java.awt.Dimension(37, 43));

        btnS.setBackground(new java.awt.Color(0, 0, 0));
        btnS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnS.setForeground(new java.awt.Color(255, 255, 255));
        btnS.setText("S");
        btnS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnS.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnS.setMinimumSize(new java.awt.Dimension(37, 43));

        btnH.setBackground(new java.awt.Color(0, 0, 0));
        btnH.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnH.setForeground(new java.awt.Color(255, 255, 255));
        btnH.setText("H");
        btnH.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnH.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnH.setMinimumSize(new java.awt.Dimension(37, 43));

        btnJ.setBackground(new java.awt.Color(0, 0, 0));
        btnJ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnJ.setForeground(new java.awt.Color(255, 255, 255));
        btnJ.setText("J");
        btnJ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnJ.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnJ.setMinimumSize(new java.awt.Dimension(37, 43));

        btnK.setBackground(new java.awt.Color(0, 0, 0));
        btnK.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnK.setForeground(new java.awt.Color(255, 255, 255));
        btnK.setText("K");
        btnK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnK.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnK.setMinimumSize(new java.awt.Dimension(37, 43));

        btnL.setBackground(new java.awt.Color(0, 0, 0));
        btnL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnL.setForeground(new java.awt.Color(255, 255, 255));
        btnL.setText("L");
        btnL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnL.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnL.setMinimumSize(new java.awt.Dimension(37, 43));

        btnCedilla.setBackground(new java.awt.Color(0, 0, 0));
        btnCedilla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCedilla.setForeground(new java.awt.Color(255, 255, 255));
        btnCedilla.setText("Ç");
        btnCedilla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCedilla.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnCedilla.setMinimumSize(new java.awt.Dimension(37, 43));

        btnTilde.setBackground(new java.awt.Color(0, 0, 0));
        btnTilde.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnTilde.setForeground(new java.awt.Color(255, 255, 255));
        btnTilde.setText("~");
        btnTilde.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTilde.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnTilde.setMinimumSize(new java.awt.Dimension(37, 43));

        btnCloseBracket.setBackground(new java.awt.Color(0, 0, 0));
        btnCloseBracket.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCloseBracket.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseBracket.setText("]");
        btnCloseBracket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseBracket.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnCloseBracket.setMinimumSize(new java.awt.Dimension(37, 43));

        btnA.setBackground(new java.awt.Color(0, 0, 0));
        btnA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnA.setForeground(new java.awt.Color(255, 255, 255));
        btnA.setText("A");
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnA.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnA.setMinimumSize(new java.awt.Dimension(37, 43));

        btnCaps.setBackground(new java.awt.Color(0, 0, 0));
        btnCaps.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCaps.setForeground(new java.awt.Color(255, 255, 255));
        btnCaps.setText("<html>Caps<br>&nbsp;Lock</html>");
        btnCaps.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEnter.setBackground(new java.awt.Color(0, 0, 0));
        btnEnter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("Enter");
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnC.setBackground(new java.awt.Color(0, 0, 0));
        btnC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnC.setForeground(new java.awt.Color(255, 255, 255));
        btnC.setText("C");
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnC.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnC.setMinimumSize(new java.awt.Dimension(37, 43));

        btnZ.setBackground(new java.awt.Color(0, 0, 0));
        btnZ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnZ.setForeground(new java.awt.Color(255, 255, 255));
        btnZ.setText("Z");
        btnZ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnZ.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnZ.setMinimumSize(new java.awt.Dimension(37, 43));

        btnN.setBackground(new java.awt.Color(0, 0, 0));
        btnN.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnN.setForeground(new java.awt.Color(255, 255, 255));
        btnN.setText("N");
        btnN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnN.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnN.setMinimumSize(new java.awt.Dimension(37, 43));

        btnM.setBackground(new java.awt.Color(0, 0, 0));
        btnM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnM.setForeground(new java.awt.Color(255, 255, 255));
        btnM.setText("M");
        btnM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnM.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnM.setMinimumSize(new java.awt.Dimension(37, 43));

        btnComma.setBackground(new java.awt.Color(0, 0, 0));
        btnComma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnComma.setForeground(new java.awt.Color(255, 255, 255));
        btnComma.setText(",");
        btnComma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnComma.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnComma.setMinimumSize(new java.awt.Dimension(37, 43));

        btnPeriod.setBackground(new java.awt.Color(0, 0, 0));
        btnPeriod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPeriod.setForeground(new java.awt.Color(255, 255, 255));
        btnPeriod.setText(".");
        btnPeriod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPeriod.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnPeriod.setMinimumSize(new java.awt.Dimension(37, 43));

        btnSemiColon.setBackground(new java.awt.Color(0, 0, 0));
        btnSemiColon.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSemiColon.setForeground(new java.awt.Color(255, 255, 255));
        btnSemiColon.setText(";");
        btnSemiColon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSemiColon.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnSemiColon.setMinimumSize(new java.awt.Dimension(37, 43));

        btnSlash.setBackground(new java.awt.Color(0, 0, 0));
        btnSlash.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSlash.setForeground(new java.awt.Color(255, 255, 255));
        btnSlash.setText("/");
        btnSlash.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSlash.setMaximumSize(new java.awt.Dimension(2147483647, 43));
        btnSlash.setMinimumSize(new java.awt.Dimension(37, 43));

        btnBackSlash.setBackground(new java.awt.Color(0, 0, 0));
        btnBackSlash.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBackSlash.setForeground(new java.awt.Color(255, 255, 255));
        btnBackSlash.setText("\\");
            btnBackSlash.setActionCommand("");
            btnBackSlash.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnBackSlash.setMaximumSize(new java.awt.Dimension(2147483647, 43));
            btnBackSlash.setMinimumSize(new java.awt.Dimension(37, 43));

            btnShift.setBackground(new java.awt.Color(0, 0, 0));
            btnShift.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnShift.setForeground(new java.awt.Color(255, 255, 255));
            btnShift.setText("Shift");
            btnShift.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            btnDown.setBackground(new java.awt.Color(0, 0, 0));
            btnDown.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnDown.setForeground(new java.awt.Color(255, 255, 255));
            btnDown.setText("▼");
            btnDown.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            btnLeft.setBackground(new java.awt.Color(0, 0, 0));
            btnLeft.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnLeft.setForeground(new java.awt.Color(255, 255, 255));
            btnLeft.setText("◄");
            btnLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            btnUp.setBackground(new java.awt.Color(0, 0, 0));
            btnUp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnUp.setForeground(new java.awt.Color(255, 255, 255));
            btnUp.setText("▲");
            btnUp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            btnRight.setBackground(new java.awt.Color(0, 0, 0));
            btnRight.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnRight.setForeground(new java.awt.Color(255, 255, 255));
            btnRight.setText("►");
            btnRight.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            btnR.setBackground(new java.awt.Color(0, 0, 0));
            btnR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnR.setForeground(new java.awt.Color(255, 255, 255));
            btnR.setText("R");
            btnR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnR.setMaximumSize(new java.awt.Dimension(2147483647, 43));
            btnR.setMinimumSize(new java.awt.Dimension(37, 43));

            btnX.setBackground(new java.awt.Color(0, 0, 0));
            btnX.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnX.setForeground(new java.awt.Color(255, 255, 255));
            btnX.setText("X");
            btnX.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnX.setMaximumSize(new java.awt.Dimension(2147483647, 43));
            btnX.setMinimumSize(new java.awt.Dimension(37, 43));

            btnB.setBackground(new java.awt.Color(0, 0, 0));
            btnB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnB.setForeground(new java.awt.Color(255, 255, 255));
            btnB.setText("B");
            btnB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnB.setMaximumSize(new java.awt.Dimension(2147483647, 43));
            btnB.setMinimumSize(new java.awt.Dimension(37, 43));

            btnD.setBackground(new java.awt.Color(0, 0, 0));
            btnD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnD.setForeground(new java.awt.Color(255, 255, 255));
            btnD.setText("D");
            btnD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnD.setMaximumSize(new java.awt.Dimension(2147483647, 43));
            btnD.setMinimumSize(new java.awt.Dimension(37, 43));

            btnV.setBackground(new java.awt.Color(0, 0, 0));
            btnV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnV.setForeground(new java.awt.Color(255, 255, 255));
            btnV.setText("V");
            btnV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnV.setMaximumSize(new java.awt.Dimension(2147483647, 43));
            btnV.setMinimumSize(new java.awt.Dimension(37, 43));

            btnSpace.setBackground(new java.awt.Color(0, 0, 0));
            btnSpace.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnSpace.setForeground(new java.awt.Color(255, 255, 255));
            btnSpace.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

            btn2.setBackground(new java.awt.Color(0, 0, 0));
            btn2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btn2.setForeground(new java.awt.Color(255, 255, 255));
            btn2.setText("<html>@<p>&nbsp; 2</html>");
            btn2.setActionCommand("<html>@<br><strong>&nbsp;2</html>");
            btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btn2.setMinimumSize(new java.awt.Dimension(37, 43));

            btn0.setBackground(new java.awt.Color(0, 0, 0));
            btn0.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btn0.setForeground(new java.awt.Color(255, 255, 255));
            btn0.setText("<html>)<p>&nbsp; 0</html>");
            btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btn0.setMinimumSize(new java.awt.Dimension(37, 43));

            btnW.setBackground(new java.awt.Color(0, 0, 0));
            btnW.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            btnW.setForeground(new java.awt.Color(255, 255, 255));
            btnW.setText("W");
            btnW.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            btnW.setMaximumSize(new java.awt.Dimension(2147483647, 43));
            btnW.setMinimumSize(new java.awt.Dimension(37, 43));

            scrollPane.setMaximumSize(new java.awt.Dimension(2147483647, 43));

            textArea.setBackground(new java.awt.Color(51, 51, 51));
            textArea.setColumns(20);
            textArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
            textArea.setForeground(new java.awt.Color(255, 255, 255));
            textArea.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    textAreaKeyPressed(evt);
                }
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    textAreaKeyReleased(evt);
                }
            });
            scrollPane.setViewportView(textArea);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnPangram)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblPangram))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnCaps)
                                .addComponent(btnTab, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnAcute, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnOpenBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnCedilla, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnTilde, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnCloseBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEnter))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(571, 571, 571)
                                            .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(445, 445, 445)
                                            .addComponent(btnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnSemiColon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnSlash, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnShift, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBackSlash, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnComma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnQuote, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBackSpace)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPangram, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPangram))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMinus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnQuote)
                        .addComponent(btnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTab, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnU, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnI, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnW, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAcute, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOpenBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnJ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCedilla, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTilde, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCloseBracket, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBackSlash, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnShift, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSemiColon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSlash, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnComma, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            getAccessibleContext().setAccessibleDescription("Developed by Yago Neno");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    // Adiconar ícone ao software.
    private void setIcon() {
        URL url = this.getClass().getResource("/imagens/icon-keyboard.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    // Ação do botão 'Pangrama' para gerar a frase.
    private void btnPangramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPangramActionPerformed
        // TODO add your handling code here:
        String phrase;
        phrase = objPangram.generatePangrams();

        lblPangram.setText(phrase);
    }//GEN-LAST:event_btnPangramActionPerformed

    // Quando pressionadas, as teclas mudam a sua cor.
    private void textAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyPressed
        // TODO add your handling code here:
        // Alguns caracteres especiais.
        switch (evt.getKeyChar()) {
            case 'ç':
            case 'Ç':
                btnCedilla.setBackground(java.awt.SystemColor.controlShadow);
                btnCedilla.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_SLASH:
            case '?':
                btnSlash.setBackground(java.awt.SystemColor.controlShadow);
                btnSlash.setForeground(java.awt.Color.black);
                break;
        }

        // Fileira 1.
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_QUOTE:
                btnQuote.setBackground(java.awt.SystemColor.controlShadow);
                btnQuote.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_1:
                btn1.setBackground(java.awt.SystemColor.controlShadow);
                btn1.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_2:
                btn2.setBackground(java.awt.SystemColor.controlShadow);
                btn2.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_3:
                btn3.setBackground(java.awt.SystemColor.controlShadow);
                btn3.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_4:
                btn4.setBackground(java.awt.SystemColor.controlShadow);
                btn4.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_5:
                btn5.setBackground(java.awt.SystemColor.controlShadow);
                btn5.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_6:
                btn6.setBackground(java.awt.SystemColor.controlShadow);
                btn6.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_7:
                btn7.setBackground(java.awt.SystemColor.controlShadow);
                btn7.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_8:
                btn8.setBackground(java.awt.SystemColor.controlShadow);
                btn8.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_9:
                btn9.setBackground(java.awt.SystemColor.controlShadow);
                btn9.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_0:
                btn0.setBackground(java.awt.SystemColor.controlShadow);
                btn0.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_EQUALS:
                btnEquals.setBackground(java.awt.SystemColor.controlShadow);
                btnEquals.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_MINUS:
                btnMinus.setBackground(java.awt.SystemColor.controlShadow);
                btnMinus.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_BACK_SPACE:
                btnBackSpace.setBackground(java.awt.SystemColor.controlShadow);
                btnBackSpace.setForeground(java.awt.Color.black);
                break;

            // Fileira 2
            case KeyEvent.VK_TAB:
                btnTab.setBackground(java.awt.SystemColor.controlShadow);
                btnTab.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_Q:
                btnQ.setBackground(java.awt.SystemColor.controlShadow);
                btnQ.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_W:
                btnW.setBackground(java.awt.SystemColor.controlShadow);
                btnW.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_E:
                btnE.setBackground(java.awt.SystemColor.controlShadow);
                btnE.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_R:
                btnR.setBackground(java.awt.SystemColor.controlShadow);
                btnR.setForeground(java.awt.Color.black);

                break;
            case KeyEvent.VK_T: {
                btnT.setBackground(java.awt.SystemColor.controlShadow);
                btnT.setForeground(java.awt.Color.black);
            }
            case KeyEvent.VK_Y:
                btnY.setBackground(java.awt.SystemColor.controlShadow);
                btnY.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_U:
                btnU.setBackground(java.awt.SystemColor.controlShadow);
                btnU.setForeground(java.awt.Color.black);

                break;
            case KeyEvent.VK_I:
                btnI.setBackground(java.awt.SystemColor.controlShadow);
                btnI.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_O:
                btnO.setBackground(java.awt.SystemColor.controlShadow);
                btnO.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_P:
                btnP.setBackground(java.awt.SystemColor.controlShadow);
                btnP.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_DEAD_ACUTE:
                btnAcute.setBackground(java.awt.SystemColor.controlShadow);
                btnAcute.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_OPEN_BRACKET:
                btnOpenBracket.setBackground(java.awt.SystemColor.controlShadow);
                btnOpenBracket.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_CAPS_LOCK:
                try {
                    if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) {
                        btnCaps.setBackground(java.awt.SystemColor.controlShadow);
                        btnCaps.setForeground(java.awt.Color.black);
                    } else {
                        btnCaps.setBackground(new java.awt.Color(0, 0, 0));
                        btnCaps.setForeground(java.awt.Color.white);
                    }
                } catch (UnsupportedOperationException ex) {
                }
                break;

            // Fileira 3
            case KeyEvent.VK_A:
                btnA.setBackground(java.awt.SystemColor.controlShadow);
                btnA.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_S:
                btnS.setBackground(java.awt.SystemColor.controlShadow);
                btnS.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_D:
                btnD.setBackground(java.awt.SystemColor.controlShadow);
                btnD.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_F:
                btnF.setBackground(java.awt.SystemColor.controlShadow);
                btnF.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_G:
                btnG.setBackground(java.awt.SystemColor.controlShadow);
                btnG.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_H:
                btnH.setBackground(java.awt.SystemColor.controlShadow);
                btnH.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_J:
                btnJ.setBackground(java.awt.SystemColor.controlShadow);
                btnJ.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_K:
                btnK.setBackground(java.awt.SystemColor.controlShadow);
                btnK.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_L:
                btnL.setBackground(java.awt.SystemColor.controlShadow);
                btnL.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_DEAD_TILDE:
                btnTilde.setBackground(java.awt.SystemColor.controlShadow);
                btnTilde.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_CLOSE_BRACKET:
                btnCloseBracket.setBackground(java.awt.SystemColor.controlShadow);
                btnCloseBracket.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_ENTER:
                btnEnter.setBackground(java.awt.SystemColor.controlShadow);
                btnEnter.setForeground(java.awt.Color.black);
                try {
                    if (textArea.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Campo Nulo\nDigite o Pangrama", "Warning", JOptionPane.WARNING_MESSAGE);
                    } else if (lblPangram.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Clique no botão acima para gerar o Pangrama", "Warning", JOptionPane.WARNING_MESSAGE);
                    } else {
                        objPangram.compareText(lblPangram, textArea, rootPane, evt);
                    }
                } catch (StringIndexOutOfBoundsException e) {
                    JOptionPane.showMessageDialog(this, "Digite o Pangrama Corretamente", "Warning", JOptionPane.WARNING_MESSAGE);
                } catch (ArithmeticException e) {
                    JOptionPane.showMessageDialog(this, "Digite o Pangrama Corretamente", "Warning", JOptionPane.WARNING_MESSAGE);
                }
                break;

            // Fileira 4.
            case KeyEvent.VK_SHIFT:
                btnShift.setBackground(java.awt.SystemColor.controlShadow);
                btnShift.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_BACK_SLASH:
                btnBackSlash.setBackground(java.awt.SystemColor.controlShadow);
                btnBackSlash.setForeground(java.awt.Color.black);

                break;
            case KeyEvent.VK_Z:
                btnZ.setBackground(java.awt.SystemColor.controlShadow);
                btnZ.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_X:
                btnX.setBackground(java.awt.SystemColor.controlShadow);
                btnX.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_C:
                btnC.setBackground(java.awt.SystemColor.controlShadow);
                btnC.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_V:
                btnV.setBackground(java.awt.SystemColor.controlShadow);
                btnV.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_B:
                btnB.setBackground(java.awt.SystemColor.controlShadow);
                btnB.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_N:
                btnN.setBackground(java.awt.SystemColor.controlShadow);
                btnN.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_M:
                btnM.setBackground(java.awt.SystemColor.controlShadow);
                btnM.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_COMMA:
                btnComma.setBackground(java.awt.SystemColor.controlShadow);
                btnComma.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_PERIOD:
                btnPeriod.setBackground(java.awt.SystemColor.controlShadow);
                btnPeriod.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_SEMICOLON:
                btnSemiColon.setBackground(java.awt.SystemColor.controlShadow);
                btnSemiColon.setForeground(java.awt.Color.black);
                break;

            // Setas & Espaço.
            case KeyEvent.VK_UP:
                btnUp.setBackground(java.awt.SystemColor.controlShadow);
                btnUp.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_RIGHT:
                btnRight.setBackground(java.awt.SystemColor.controlShadow);
                btnRight.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_LEFT:
                btnLeft.setBackground(java.awt.SystemColor.controlShadow);
                btnLeft.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_DOWN:
                btnDown.setBackground(java.awt.SystemColor.controlShadow);
                btnDown.setForeground(java.awt.Color.black);
                break;

            case KeyEvent.VK_SPACE:
                btnSpace.setBackground(java.awt.SystemColor.controlShadow);
                break;
        }
    }//GEN-LAST:event_textAreaKeyPressed

    // Quando soltadas as teclas voltam a cor padrão.
    private void textAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyReleased
        // TODO add your handling code here:
        // Alguns caracteres especiais.
        switch (evt.getKeyChar()) {
            case 'ç':
            case 'Ç':
                btnCedilla.setBackground(new java.awt.Color(0, 0, 0));
                btnCedilla.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_SLASH:
            case '?':
                btnSlash.setBackground(new java.awt.Color(0, 0, 0));
                btnSlash.setForeground(java.awt.Color.white);
                break;
        }

        // Fileira 1.
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_QUOTE:
                btnQuote.setBackground(new java.awt.Color(0, 0, 0));
                btnQuote.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_1:
                btn1.setBackground(new java.awt.Color(0, 0, 0));
                btn1.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_2:
                btn2.setBackground(new java.awt.Color(0, 0, 0));
                btn2.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_3:
                btn3.setBackground(new java.awt.Color(0, 0, 0));
                btn3.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_4:
                btn4.setBackground(new java.awt.Color(0, 0, 0));
                btn4.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_5:
                btn5.setBackground(new java.awt.Color(0, 0, 0));
                btn5.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_6:
                btn6.setBackground(new java.awt.Color(0, 0, 0));
                btn6.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_7:
                btn7.setBackground(new java.awt.Color(0, 0, 0));
                btn7.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_8:
                btn8.setBackground(new java.awt.Color(0, 0, 0));
                btn8.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_9:
                btn9.setBackground(new java.awt.Color(0, 0, 0));
                btn9.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_0:
                btn0.setBackground(new java.awt.Color(0, 0, 0));
                btn0.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_EQUALS:
                btnEquals.setBackground(new java.awt.Color(0, 0, 0));
                btnEquals.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_MINUS:
                btnMinus.setBackground(new java.awt.Color(0, 0, 0));
                btnMinus.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_BACK_SPACE:
                btnBackSpace.setBackground(new java.awt.Color(0, 0, 0));
                btnBackSpace.setForeground(java.awt.Color.white);
                break;

            // Fileira 2.
            case KeyEvent.VK_TAB:
                btnTab.setBackground(new java.awt.Color(0, 0, 0));
                btnTab.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_Q:
                btnQ.setBackground(new java.awt.Color(0, 0, 0));
                btnQ.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_W:
                btnW.setBackground(new java.awt.Color(0, 0, 0));
                btnW.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_E:
                btnE.setBackground(new java.awt.Color(0, 0, 0));
                btnE.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_R:
                btnR.setBackground(new java.awt.Color(0, 0, 0));
                btnR.setForeground(java.awt.Color.white);

                break;
            case KeyEvent.VK_T: {
                btnT.setBackground(new java.awt.Color(0, 0, 0));
                btnT.setForeground(java.awt.Color.white);
            }
            case KeyEvent.VK_Y:
                btnY.setBackground(new java.awt.Color(0, 0, 0));
                btnY.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_U:
                btnU.setBackground(new java.awt.Color(0, 0, 0));
                btnU.setForeground(java.awt.Color.white);

                break;
            case KeyEvent.VK_I:
                btnI.setBackground(new java.awt.Color(0, 0, 0));
                btnI.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_O:
                btnO.setBackground(new java.awt.Color(0, 0, 0));
                btnO.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_P:
                btnP.setBackground(new java.awt.Color(0, 0, 0));
                btnP.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_DEAD_ACUTE:
                btnAcute.setBackground(new java.awt.Color(0, 0, 0));
                btnAcute.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_OPEN_BRACKET:
                btnOpenBracket.setBackground(new java.awt.Color(0, 0, 0));
                btnOpenBracket.setForeground(java.awt.Color.white);
                break;

            // Fileira 3.
            case KeyEvent.VK_A:
                btnA.setBackground(new java.awt.Color(0, 0, 0));
                btnA.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_S:
                btnS.setBackground(new java.awt.Color(0, 0, 0));
                btnS.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_D:
                btnD.setBackground(new java.awt.Color(0, 0, 0));
                btnD.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_F:
                btnF.setBackground(new java.awt.Color(0, 0, 0));
                btnF.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_G:
                btnG.setBackground(new java.awt.Color(0, 0, 0));
                btnG.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_H:
                btnH.setBackground(new java.awt.Color(0, 0, 0));
                btnH.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_J:
                btnJ.setBackground(new java.awt.Color(0, 0, 0));
                btnJ.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_K:
                btnK.setBackground(new java.awt.Color(0, 0, 0));
                btnK.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_L:
                btnL.setBackground(new java.awt.Color(0, 0, 0));
                btnL.setForeground(java.awt.Color.white);
                break;

            case 'ç':
            case 'Ç':
                btnCedilla.setBackground(new java.awt.Color(0, 0, 0));
                btnCedilla.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_DEAD_TILDE:
                btnTilde.setBackground(new java.awt.Color(0, 0, 0));
                btnTilde.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_CLOSE_BRACKET:
                btnCloseBracket.setBackground(new java.awt.Color(0, 0, 0));
                btnCloseBracket.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_ENTER:
                btnEnter.setBackground(new java.awt.Color(0, 0, 0));
                btnEnter.setForeground(java.awt.Color.white);
                break;

            // Fileira 4.
            case KeyEvent.VK_SHIFT:
                btnShift.setBackground(new java.awt.Color(0, 0, 0));
                btnShift.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_BACK_SLASH:
                btnBackSlash.setBackground(new java.awt.Color(0, 0, 0));
                btnBackSlash.setForeground(java.awt.Color.white);

                break;
            case KeyEvent.VK_Z:
                btnZ.setBackground(new java.awt.Color(0, 0, 0));
                btnZ.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_X:
                btnX.setBackground(new java.awt.Color(0, 0, 0));
                btnX.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_C:
                btnC.setBackground(new java.awt.Color(0, 0, 0));
                btnC.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_V:
                btnV.setBackground(new java.awt.Color(0, 0, 0));
                btnV.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_B:
                btnB.setBackground(new java.awt.Color(0, 0, 0));
                btnB.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_N:
                btnN.setBackground(new java.awt.Color(0, 0, 0));
                btnN.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_M:
                btnM.setBackground(new java.awt.Color(0, 0, 0));
                btnM.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_COMMA:
                btnComma.setBackground(new java.awt.Color(0, 0, 0));
                btnComma.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_PERIOD:
                btnPeriod.setBackground(new java.awt.Color(0, 0, 0));
                btnPeriod.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_SEMICOLON:
                btnSemiColon.setBackground(new java.awt.Color(0, 0, 0));
                btnSemiColon.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_SLASH:
            case '?':
                btnSlash.setBackground(new java.awt.Color(0, 0, 0));
                btnSlash.setForeground(java.awt.Color.white);
                break;

            // Setas & Espaço.
            case KeyEvent.VK_UP:
                btnUp.setBackground(new java.awt.Color(0, 0, 0));
                btnUp.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_RIGHT:
                btnRight.setBackground(new java.awt.Color(0, 0, 0));
                btnRight.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_LEFT:
                btnLeft.setBackground(new java.awt.Color(0, 0, 0));
                btnLeft.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_DOWN:
                btnDown.setBackground(new java.awt.Color(0, 0, 0));
                btnDown.setForeground(java.awt.Color.white);
                break;

            case KeyEvent.VK_SPACE:
                btnSpace.setBackground(new java.awt.Color(0, 0, 0));
                break;
        }
    }//GEN-LAST:event_textAreaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeyboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeyboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeyboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeyboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeyboardScreen().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnAcute;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnBackSlash;
    private javax.swing.JButton btnBackSpace;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCaps;
    private javax.swing.JButton btnCedilla;
    private javax.swing.JButton btnCloseBracket;
    private javax.swing.JButton btnComma;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnOpenBracket;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnPangram;
    private javax.swing.JButton btnPeriod;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnQuote;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnSemiColon;
    private javax.swing.JButton btnShift;
    private javax.swing.JButton btnSlash;
    private javax.swing.JButton btnSpace;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnTab;
    private javax.swing.JButton btnTilde;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JLabel lblPangram;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
